var scale = 1;
var dxBase = 0;
var dyBase = 0;
var dzBase = -100;
var xOffsetRod = 28;
var yOffsetRod = 10.75;
var maxLevel = 7;
var cameraPositionNode;
var basePositionNode;
var baseNode;
var discMinHeight = 16.75*scale;
var discMaxHeight = 19.75*scale;
var discs = [];
var rods = [];